# Generated by Django 3.2.4 on 2021-06-30 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('rut_servicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='rut')),
                ('razon_servicio', models.CharField(max_length=50, verbose_name=' razon social')),
                ('descripcion_servicio', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('servicio_servicio', models.CharField(max_length=50, verbose_name='Servicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.servicios'),
            preserve_default=False,
        ),
    ]
